"""Application constants"""

# Pagination
DEFAULT_PAGE = 1
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# Cache TTL (in seconds)
CACHE_TTL_SHORT = 300  # 5 minutes
CACHE_TTL_MEDIUM = 1800  # 30 minutes
CACHE_TTL_LONG = 3600  # 1 hour

# Contact status
CONTACT_STATUS_NEW = "new"
CONTACT_STATUS_CONTACTED = "contacted"
CONTACT_STATUS_CONVERTED = "converted"
CONTACT_STATUS_REJECTED = "rejected"

CONTACT_STATUSES = [
    CONTACT_STATUS_NEW,
    CONTACT_STATUS_CONTACTED,
    CONTACT_STATUS_CONVERTED,
    CONTACT_STATUS_REJECTED,
]

# Callback status
CALLBACK_STATUS_PENDING = "pending"
CALLBACK_STATUS_SCHEDULED = "scheduled"
CALLBACK_STATUS_COMPLETED = "completed"
CALLBACK_STATUS_CANCELLED = "cancelled"

CALLBACK_STATUSES = [
    CALLBACK_STATUS_PENDING,
    CALLBACK_STATUS_SCHEDULED,
    CALLBACK_STATUS_COMPLETED,
    CALLBACK_STATUS_CANCELLED,
]
